application: google.com:codebin
version: 1
runtime: python
api_version: 1

skip_files: |
  ^(.*/)?(
  (index\.yaml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*/RCS/.*)|
  (\..*)|
  (BUILD)|
  (Makefile)|
  (.*/closure-.*)|
  (bin/.*)|
  )$

handlers:

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  expiration: '3650d'

- url: /static
  static_dir: static

- url: /deps.js
  static_files: static/deps.js
  upload: /deps.js

- url: /.*
  script: main.py

- url: /
  script: main.py